In [1]:
import pandas as pd
from datetime import datetime

In [2]:
returns = pd.read_csv('Returns.csv')
returns

     return_date  product_id  store_id  quantity
0       1/1/1997         250         6         1
1       1/1/1997         628         6         1
2       1/1/1997         869         6         1
3       1/2/1997         469        11         1
4       1/2/1997         532        23         2
...          ...         ...       ...       ...
7082  12/30/1998        1037        11         2
7083  12/30/1998        1048        10         1
7084  12/30/1998        1065        10         1
7085  12/30/1998        1154        11         1
7086  12/30/1998        1291        11         1

[7087 rows x 4 columns]

In [3]:
returns.isna().sum()

return_date    0
product_id     0
store_id       0
quantity       0
dtype: int64

In [4]:
returns.drop_duplicates(inplace=True)

In [5]:
returns.dtypes

return_date      str
product_id     int64
store_id       int64
quantity       int64
dtype: object

In [6]:
returns['return_date'] = pd.to_datetime(returns['return_date'], format='%m/%d/%Y')

In [7]:
returns

     return_date  product_id  store_id  quantity
0     1997-01-01         250         6         1
1     1997-01-01         628         6         1
2     1997-01-01         869         6         1
3     1997-01-02         469        11         1
4     1997-01-02         532        23         2
...          ...         ...       ...       ...
7082  1998-12-30        1037        11         2
7083  1998-12-30        1048        10         1
7084  1998-12-30        1065        10         1
7085  1998-12-30        1154        11         1
7086  1998-12-30        1291        11         1

[7082 rows x 4 columns]

In [8]:
returns.to_csv('C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\retail company\\cleaned datasets\\returns.csv', index=False)