In [1]:
import pandas as pd
from datetime import datetime

In [2]:
calendar = pd.read_csv('Calendar.csv')
calendar

           date
0      1/1/1997
1      1/2/1997
2      1/3/1997
3      1/4/1997
4      1/5/1997
..          ...
725  12/27/1998
726  12/28/1998
727  12/29/1998
728  12/30/1998
729  12/31/1998

[730 rows x 1 columns]

In [3]:
calendar.isna().sum()

date    0
dtype: int64

In [4]:
calendar.duplicated().sum()

np.int64(0)

In [5]:
calendar.dtypes

date    str
dtype: object

In [6]:
calendar['date'] = pd.to_datetime(calendar['date'],format='%m/%d/%Y')
calendar

          date
0   1997-01-01
1   1997-01-02
2   1997-01-03
3   1997-01-04
4   1997-01-05
..         ...
725 1998-12-27
726 1998-12-28
727 1998-12-29
728 1998-12-30
729 1998-12-31

[730 rows x 1 columns]

In [7]:
calendar.dtypes

date    datetime64[us]
dtype: object

In [8]:
calendar['year'] = calendar['date'].dt.year
calendar['month'] = calendar['date'].dt.month
calendar['month_name'] = calendar['date'].dt.month_name()
calendar['day'] = calendar['date'].dt.day
calendar['day_of_week'] = calendar['date'].dt.day_of_week
calendar['week_of_year'] = calendar['date'].dt.isocalendar().week
calendar['quarter'] = calendar['date'].dt.quarter

In [9]:
calendar

,date,year,month,month_name,day,day_of_week,week_of_year,quarter
0,1997-01-01,1997,1,January,1,2,1,1
1,1997-01-02,1997,1,January,2,3,1,1
2,1997-01-03,1997,1,January,3,4,1,1
3,1997-01-04,1997,1,January,4,5,1,1
4,1997-01-05,1997,1,January,5,6,1,1
...,...,...,...,...,...,...,...,...
725,1998-12-27,1998,12,December,27,6,52,4
726,1998-12-28,1998,12,December,28,0,53,4
727,1998-12-29,1998,12,December,29,1,53,4
728,1998-12-30,1998,12,December,30,2,53,4
729,1998-12-31,1998,12,December,31,3,53,4

In [10]:
calendar.dtypes

date            datetime64[us]
year                     int32
month                    int32
month_name                 str
day                      int32
day_of_week              int32
week_of_year            UInt32
quarter                  int32
dtype: object

In [11]:
calendar['quarter'] = calendar['quarter'].astype('str')

In [12]:
calendar['quarter'] = 'Q-' + calendar['quarter']

In [13]:
calendar

          date  year  month month_name  day  day_of_week  week_of_year quarter
0   1997-01-01  1997      1    January    1            2             1     Q-1
1   1997-01-02  1997      1    January    2            3             1     Q-1
2   1997-01-03  1997      1    January    3            4             1     Q-1
3   1997-01-04  1997      1    January    4            5             1     Q-1
4   1997-01-05  1997      1    January    5            6             1     Q-1
..         ...   ...    ...        ...  ...          ...           ...     ...
725 1998-12-27  1998     12   December   27            6            52     Q-4
726 1998-12-28  1998     12   December   28            0            53     Q-4
727 1998-12-29  1998     12   December   29            1            53     Q-4
728 1998-12-30  1998     12   December   30            2            53     Q-4
729 1998-12-31  1998     12   December   31            3            53     Q-4

[730 rows x 8 columns]

In [15]:
calendar.to_csv('C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\retail company\\cleaned datasets\\calendar.csv', index=False)